# Generated by Django 6.0.3 on 2026-03-23 20:58

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[("ADMIN", "ADMIN"), ("EMPLOYE", "EMPLOYE")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="RoleUtilisateur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_utilisateurs",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "db_table": "role_utilisateur",
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("login_utilisateur", models.CharField(max_length=255, unique=True)),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("mot_de_passe", models.CharField(max_length=255)),
                (
                    "embedding_facial",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
                ("departement", models.CharField(blank=True, max_length=50, null=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "roles",
                    models.ManyToManyField(
                        related_name="utilisateurs",
                        through="core.RoleUtilisateur",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "db_table": "utilisateur",
            },
        ),
        migrations.AddField(
            model_name="roleutilisateur",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_utilisateurs",
                to="core.utilisateur",
            ),
        ),
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("VALIDE", "Validé"), ("NON_VALIDE", "Non validé")],
                        max_length=20,
                    ),
                ),
                ("horodatage", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[("ENTREE", "ENTREE"), ("SORTIE", "SORTIE")],
                        max_length=10,
                    ),
                ),
                ("score_confiance", models.FloatField()),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="core.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "pointage",
            },
        ),
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RETARD", "RETARD"),
                            ("ABSENCE", "ABSENCE"),
                            ("UTILISATEUR_INCONNU", "UTILISATEUR_INCONNU"),
                            ("ECHEC_RECONNAISSANCE", "ECHEC_RECONNAISSANCE"),
                            ("DOUBLE_POINTAGE", "DOUBLE_POINTAGE"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NOUVELLE", "NOUVELLE"),
                            ("VUE", "VUE"),
                            ("TRAITEE", "TRAITEE"),
                        ],
                        default="NOUVELLE",
                        max_length=20,
                    ),
                ),
                (
                    "pointage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes",
                        to="core.pointage",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes",
                        to="core.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "alerte",
            },
        ),
        migrations.AlterUniqueTogether(
            name="roleutilisateur",
            unique_together={("role", "utilisateur")},
        ),
    ]
