# Generated by Django 6.0.3 on 2026-03-24 09:16

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("ID_Utilisateur", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=255)),
                ("Prenom", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=255, unique=True)),
                (
                    "Login_Utilisateur",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("Password", models.CharField(max_length=255)),
                (
                    "Embedding_facial",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=128, null=True
                    ),
                ),
                ("Departement", models.CharField(blank=True, max_length=50, null=True)),
                ("Date_debut", models.DateField(auto_now_add=True)),
                ("Date_fin", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
            },
        ),
    ]
