# Generated by Django 6.0.3 on 2026-03-24 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("ENTREE", "Entrée"), ("SORTIE", "Sortie")],
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("Validé", "Validé"), ("Non validé", "Non validé")],
                        default="Validé",
                        max_length=20,
                    ),
                ),
                (
                    "score_confiance",
                    models.FloatField(
                        help_text="Précision de l'IA (0.0 à 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="Employee.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointage",
                "verbose_name_plural": "Pointages",
                "ordering": ["-horodatage"],
            },
        ),
    ]
