# Generated by Django 6.0.3 on 2026-03-24 23:00

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0002_pointage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("ID_Role", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Nom",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("EMPLOYE", "Employé")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle",
                "db_table": "Rôle",
            },
        ),
        migrations.RemoveField(
            model_name="pointage",
            name="employee",
        ),
        migrations.AlterModelOptions(
            name="pointage",
            options={},
        ),
        migrations.RemoveField(
            model_name="pointage",
            name="id",
        ),
        migrations.AddField(
            model_name="pointage",
            name="ID_Pointage",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pointage",
            name="score_confiance",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ]
            ),
        ),
        migrations.AlterModelTable(
            name="pointage",
            table="Pointage",
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("ID_Utilisateur", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Login_Utilisateur",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("Nom", models.CharField(max_length=255)),
                ("Prenom", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=255, unique=True)),
                ("Mot_de_passe", models.CharField(max_length=255)),
                (
                    "Embedding_facial",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=128, null=True
                    ),
                ),
                ("Departement", models.CharField(blank=True, max_length=50, null=True)),
                ("Date_debut", models.DateField(auto_now_add=True)),
                ("Date_fin", models.DateField(blank=True, null=True)),
                (
                    "roles",
                    models.ManyToManyField(
                        related_name="utilisateurs", to="Employee.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "Utilisateur",
            },
        ),
        migrations.CreateModel(
            name="Alerte",
            fields=[
                ("ID_Alerte", models.AutoField(primary_key=True, serialize=False)),
                ("Type", models.CharField(max_length=50)),
                ("Description", models.TextField()),
                ("Date_creation", models.DateTimeField(auto_now_add=True)),
                ("Statut", models.CharField(default="NOUVELLE", max_length=20)),
                (
                    "pointage",
                    models.ForeignKey(
                        db_column="ID_Pointage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Employee.pointage",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        db_column="ID_Utilisateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Employee.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte",
                "verbose_name_plural": "Alertes",
                "db_table": "Alertes",
            },
        ),
        migrations.AddField(
            model_name="pointage",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_Utilisateur",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pointages",
                to="Employee.utilisateur",
            ),
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
