# Generated by Django 6.0.3 on 2026-03-25 08:20

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Employee",
            "0003_role_remove_pointage_employee_alter_pointage_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="Photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="Embedding_facial",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=512, null=True
            ),
        ),
    ]
