# Generated by Django 6.0.3 on 2026-03-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="nom",
            field=models.CharField(
                choices=[
                    ("EMPLOYE", "EMPLOYE"),
                    ("ADMIN", "ADMIN"),
                    ("ADMINDJANGO", "ADMINDJANGO"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
