# Generated by Django 6.0.3 on 2026-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_role_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="nom",
            field=models.CharField(
                choices=[
                    ("employé", "employé"),
                    ("admin", "admin"),
                    ("admindjango", "admindjango"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
