# Generated by Django 6.0.3 on 2026-03-25 07:54

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_admindjango_to_acces_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="nom",
            field=models.CharField(
                choices=[
                    ("employé", "employé"),
                    ("admin", "admin"),
                    ("acces_total", "acces_total"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="embedding_facial",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=512, null=True
            ),
        ),
    ]
