# Generated by Django 6.0.3 on 2026-03-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_embedding_facial_to_512"),
        ("accounts", "0006_alter_role_nom"),
    ]

    operations = []
