# Generated by Django 5.1.15 on 2026-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulesettings",
            name="arrival_window_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedulesettings",
            name="arrival_window_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedulesettings",
            name="departure_window_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedulesettings",
            name="departure_window_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedulesettings",
            name="required_daily_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
