# Generated by Django 6.0.3 on 2026-03-24 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RETARD", "RETARD"),
                            ("ABSENCE", "ABSENCE"),
                            ("UTILISATEUR_INCONNU", "UTILISATEUR_INCONNU"),
                            ("ECHEC_RECONNAISSANCE", "ECHEC_RECONNAISSANCE"),
                            ("DOUBLE_POINTAGE", "DOUBLE_POINTAGE"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NOUVELLE", "NOUVELLE"),
                            ("VUE", "VUE"),
                            ("TRAITEE", "TRAITEE"),
                        ],
                        default="NOUVELLE",
                        max_length=20,
                    ),
                ),
                (
                    "pointage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes",
                        to="attendance.pointage",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "alerte",
                "ordering": ["-date_creation"],
            },
        ),
    ]
