# Generated by Django 5.1.15 on 2026-04-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerte",
            name="type",
            field=models.CharField(
                choices=[
                    ("RETARD", "RETARD"),
                    ("ABSENCE", "ABSENCE"),
                    ("UTILISATEUR_INCONNU", "UTILISATEUR_INCONNU"),
                    ("ECHEC_RECONNAISSANCE", "ECHEC_RECONNAISSANCE"),
                    ("TENTATIVE_FRAUDE", "TENTATIVE_FRAUDE"),
                    ("DOUBLE_POINTAGE", "DOUBLE_POINTAGE"),
                ],
                max_length=50,
            ),
        ),
    ]
