# Generated by Django 5.1.15 on 2026-04-15 18:58

from django.db import migrations, models


def backfill_security_alerts(apps, schema_editor):
    Alerte = apps.get_model("alerts", "Alerte")
    Pointage = apps.get_model("attendance", "Pointage")

    incident_types = ["UTILISATEUR_INCONNU", "ECHEC_RECONNAISSANCE", "TENTATIVE_FRAUDE"]
    descriptions = {
        "UTILISATEUR_INCONNU": "Utilisateur inconnu détecté par la borne.",
        "ECHEC_RECONNAISSANCE": "Visage non détecté ou reconnaissance échouée.",
        "TENTATIVE_FRAUDE": "Tentative de fraude détectée par le contrôle biométrique.",
    }
    existing_pointage_ids = set(
        Alerte.objects.exclude(pointage_id__isnull=True).values_list("pointage_id", flat=True)
    )

    for pointage in Pointage.objects.filter(
        statut="NON_VALIDE",
        origine="POINTEUSE",
        incident_type__in=incident_types,
    ).iterator():
        if pointage.id in existing_pointage_ids:
            continue

        details = pointage.details if isinstance(pointage.details, dict) else {}
        Alerte.objects.create(
            utilisateur_id=pointage.utilisateur_id,
            pointage_id=pointage.id,
            type=pointage.incident_type,
            description=details.get("message") or descriptions.get(pointage.incident_type, "Alerte de sécurité biométrique."),
            event_status=details.get("status", ""),
            device_name=getattr(pointage, "device_name", "") or "",
            details=details,
            statut="NOUVELLE",
            masquee=False,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_alerte_front_event_fields"),
        ("attendance", "0003_pointage_incident_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerte",
            name="masquee",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="alerte",
            name="type",
            field=models.CharField(
                choices=[
                    ("RETARD", "Retard"),
                    ("ABSENCE", "Absence"),
                    ("UTILISATEUR_INCONNU", "Utilisateur inconnu"),
                    ("ECHEC_RECONNAISSANCE", "Visage non détecté"),
                    ("TENTATIVE_FRAUDE", "Tentative de fraude"),
                    ("DOUBLE_POINTAGE", "Double pointage"),
                ],
                max_length=50,
            ),
        ),
        migrations.RunPython(backfill_security_alerts, migrations.RunPython.noop),
    ]
