# Generated by Django 5.1.15 on 2026-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_alerte_masquee_alter_alerte_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerte",
            name="type",
            field=models.CharField(
                choices=[
                    ("RETARD", "Retard"),
                    ("ABSENCE", "Absence"),
                    ("DEPART_ANTICIPE", "Départ anticipé"),
                    ("JOURNEE_COURTE", "Journée trop courte"),
                    ("DEMANDE_PLANNING", "Demande planning"),
                    ("UTILISATEUR_INCONNU", "Utilisateur inconnu"),
                    ("ECHEC_RECONNAISSANCE", "Visage non détecté"),
                    ("TENTATIVE_FRAUDE", "Tentative de fraude"),
                    ("DOUBLE_POINTAGE", "Double pointage"),
                ],
                max_length=50,
            ),
        ),
    ]
