# Generated by Django 6.0.3 on 2026-03-24 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("VALIDE", "Validé"), ("NON_VALIDE", "Non validé")],
                        max_length=20,
                    ),
                ),
                ("horodatage", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[("ENTREE", "ENTREE"), ("SORTIE", "SORTIE")],
                        max_length=10,
                    ),
                ),
                ("score_confiance", models.FloatField()),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pointage",
                "ordering": ["-horodatage"],
            },
        ),
    ]
