# Generated by Django 5.1.15 on 2026-04-14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_pointage_origine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='utilisateur',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='pointages',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='pointage',
            name='incident_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('UTILISATEUR_INCONNU', 'UTILISATEUR_INCONNU'),
                    ('ECHEC_RECONNAISSANCE', 'ECHEC_RECONNAISSANCE'),
                    ('TENTATIVE_FRAUDE', 'TENTATIVE_FRAUDE'),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='pointage',
            name='device_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pointage',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
